# Generated by Django 2.2 on 2020-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200217_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://image.flaticon.com/icons/svg/1377/1377194.svg', max_length=500),
        ),
    ]
