# Generated by Django 2.1.7 on 2020-03-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='address_bar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
