# Generated by Django 2.2 on 2020-02-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='previous_work',
            new_name='previous',
        ),
    ]
