# Generated by Django 2.2 on 2020-02-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdf', '0002_auto_20200226_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='previous',
            new_name='previous_work',
        ),
    ]
