# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-08-17 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20200817_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='last_4',
        ),
        migrations.AddField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='stripe_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
